//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortHotelRev2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResortDBEntities : DbContext
    {
        public ResortDBEntities()
            : base("name=ResortDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOOKUPRole> LOOKUPRoles { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRoles { get; set; }
        public virtual DbSet<SYSRoomsTable> SYSRoomsTables { get; set; }
        public virtual DbSet<SYSRoomReservedTable> SYSRoomReservedTables { get; set; }
        public virtual DbSet<SYSOccupiedRoomTable> SYSOccupiedRoomTables { get; set; }
        public virtual DbSet<SYSUser> SYSUsers { get; set; }
        public virtual DbSet<SYSGuestTable> SYSGuestTables { get; set; }
        public virtual DbSet<SYSUserProfile> SYSUserProfiles { get; set; }
        public virtual DbSet<SYSGuestToRoomTable> SYSGuestToRoomTables { get; set; }
        public virtual DbSet<SYSReservationTable> SYSReservationTables { get; set; }

        public System.Data.Entity.DbSet<ResortHotelRev2.Models.ViewModel.RoomAndReservationModel> RoomAndReservationModels { get; set; }
    }
}
