//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortHotelRev2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSOccupiedRoomTable
    {
        public int Id { get; set; }
        public System.DateTime CheckIN { get; set; }
        public System.DateTime CheckOUT { get; set; }
        public int RoomID { get; set; }
        public int ReservationID { get; set; }
    
        public virtual SYSRoomsTable SYSRoomsTable { get; set; }
        public virtual SYSReservationTable SYSReservationTable { get; set; }
    }
}
