//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResortHotelRev2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSRoomReservedTable
    {
        public int Id { get; set; }
        public int NumberOfRooms { get; set; }
        public int ReservationId { get; set; }
        public string Status { get; set; }
    
        public virtual SYSReservationTable SYSReservationTable { get; set; }
    }
}
